clean and format

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,4 +1,10 @@
 #!/usr/bin/env bash
 
-export PATH=/usr/local/bin:$PATH
-node './hooks/pre-commit-test.js'
+npm test
+CODE=$?
+if [[ "$CODE" == "0" ]]; then
+	echo -e "\e[1;31m  npm test success! \e[0m"
+else
+	echo -e "\e[1;32m  npm test failed with exit code: ${CODE} \e[0m"
+fi
+exit $CODE
